version: '3.9'
services:
  pgAdmin:
    image: dpage/pgadmin4:6.17
    restart: always
    volumes:
      - pg-admin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    ports:
      - ${PG_ADMIN_PORT}:80
    container_name: ${PG_ADMIN_CONTAINER_NAME}

volumes:
  pg-admin:
    name: pg-admin
    external: false