version: '3.9'
services:
  db:
    image: mongo:6.0.4
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
      - mongodb:/data/configdb

volumes:
  mongodb:
    name: mongodb
    external: false