version: '3.9'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    container_name: ${DB_NAME}

volumes:
  postgres-db:
    name: postgres-db
    external: false